name: dutch_pay_calculator
description: "금액과 인원수를 입력하면 1인당 금액과 나머지를 계산해주는 더치페이 계산기 (Flutter)."
publish_to: 'none'

version: 1.0.4+8

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  google_mobile_ads: ^8.0.0
  share_plus: ^13.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
