name: dutch_pay_calculator
description: "금액과 인원수를 입력하면 1인당 금액과 나머지를 계산해주는 더치페이 계산기 (Flutter)."
publish_to: 'none'

version: 1.0.7+12

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  google_mobile_ads: ^9.0.0
  share_plus: ^13.1.0
  package_info_plus: ^10.1.0
  in_app_purchase: ^3.2.0
  shared_preferences: ^2.5.5
  in_app_review: ^2.0.10
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  image_path: "icon_design/icon3_master.png"
  android: true
  ios: true
  remove_alpha_ios: true
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - docs/legal/
